PREFIX :<http://www.semanticweb.org/ontologies/2009/10/Ontology1258388399307.owl#>

SELECT DISTINCT ?Professor
{
  ?Professor a :Professor .
  ?Prof_do_IME a :Professor .
  ?departamento a :Departamento .
  
  ?Professor :orientado_por ?Prof_do_IME .
  ?Prof_do_IME :afiliado_a ?departamento .
  ?departamento :pertence :IME
}
