PREFIX :<http://www.semanticweb.org/ontologies/2009/10/Ontology1258388399307.owl#>

SELECT DISTINCT ?um_professor ?co_autor
{
  ?mesmo_trabalho a :Trabalho .
  ?mesmo_departamento a :Departamento .
  ?um_professor a :Professor .
  ?co_autor a :Professor .
  
  ?um_professor :publicou ?mesmo_trabalho .
  ?co_autor  :publicou ?mesmo_trabalho .
  ?um_professor  :afiliado_a ?mesmo_departamento .
  ?co_autor  :afiliado_a ?mesmo_departamento .
  
  FILTER (?um_professor != ?co_autor)
}
