PREFIX :<http://www.semanticweb.org/ontologies/2009/10/Ontology1258388399307.owl#>

SELECT DISTINCT ?Aluno
{
  ?Aluno a :Aluno .
  ?artigo a :Artigo_em_Revista .
  ?Professor a :Professor .
	?revista a :Revista .
  
  ?Aluno :publicou ?artigo .
  ?Professsor :publicou ?artigo .
  ?Professor :orientador_de ?Aluno .
  ?artigo :publicado_na ?revista
}

