PREFIX projeto:<http://www.semanticweb.org/ontologies/2009/10/Ontology1258388399307.owl#>

SELECT ?professor
{
  ?professor a projeto:Professor .
  ?artigo_em_conferencia a projeto:Artigo_em_Conferencia .
  
  ?professor projeto:publicou ?artigo .
  ?artigo_em_conferencia projeto:publicou_em projeto:2008 .
  ?artigo_em_conferencia projeto:apresentado_em projeto:Brasil
}
