PREFIX :<http://www.semanticweb.org/ontologies/2009/10/Ontology1258388399307.owl#>

SELECT *
{
  ?Professor a :Professor .
  
  ?Professor :publicou :Secondary_stress_in_two_varieties_of_Portuguese_and_the_Sotaq_optimality_based_computer_program
}
