PREFIX :<http://www.semanticweb.org/ontologies/2009/10/Ontology1258388399307.owl#>

SELECT DISTINCT ?professor
{
  ?professor a :Professor .
  ?artigo_em_conferencia a :Artigo_em_Conferencia .
  
  ?professor :publicou ?artigo_em_conferencia .
  ?artigo_em_conferencia :publicou_em :2007 .
  ?artigo_em_conferencia :apresentado_em :Brasil
}
