PREFIX :<http://www.semanticweb.org/ontologies/2009/10/Ontology1258388399307.owl#>

SELECT ?professor
{
  ?professor a :Professor .
  ?artigo a :Artigo .
  
  ?professor :publicou ?artigo .
  ?artigo :publicou_em :2008
}
