PREFIX :<http://www.semanticweb.org/ontologies/2009/10/Ontology1258388399307.owl#>

SELECT ?Professor
{
  ?Professor a :Professor .
  ?pais a :Pais .
  
  ?Professor :morou_em ?pais .
  :Europa :contem_o ?pais
}
